### ISSUE TITLE
The downloads path for release 0.6.0 snap does not match toolchain-installer.sh expectations

### ISSUE THREAD

**Issue by vstrakh** [openXC7/openXC7-snap#3]
It seems all the previous releases had 'v' in front of the actual version number, and toolchain-installer.sh relies on it.
For some reason the release 0.6.0 is not found at the 'v0.6.0' path but it's '0.6.0', this breaks the toolchain-installer.

**Comment by hansfbaier** [comment]
OK fixed.
Chose to adapt the toolchain installer for consistency.
https://github.com/openXC7/toolchain-installer/commit/d6365f9a4607aa3452697f71eae39fb638070e1b

**Comment by hansfbaier** [comment]
@vstrakh Thanks for reporting this!
